<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up()
    {
        Schema::create('tickets', function (Blueprint $table) {
            $table->id();
            $table->string('ticket_id')->unique()->comment('Autogenerated ticket number');
            $table->foreignId('user_id')->constrained()->comment('User who created the ticket');
            $table->string('subject');
            $table->string('attachment')->nullable();
            $table->text('description');
            $table->enum('status', ['open', 'pending', 'resolved', 'closed'])->default('open');
            $table->timestamp('resolved_at')->nullable();
            $table->timestamp('closed_at')->nullable();
            $table->integer('response_time')->nullable()->comment('In minutes');
            $table->softDeletes();
            $table->timestamps();
            // Indexes
            $table->index('status');
            $table->index('priority');
            $table->index('category');
            $table->index('assigned_to');
        });
    }

    public function down()
    {
        Schema::dropIfExists('tickets');
    }
};
